# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-20 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ninjas_app', '0002_auto_20170920_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ninja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Dojos',
            new_name='Dojo',
        ),
        migrations.RemoveField(
            model_name='ninjas',
            name='dojo',
        ),
        migrations.DeleteModel(
            name='Ninjas',
        ),
        migrations.AddField(
            model_name='ninja',
            name='dojo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ninjas', to='Ninjas_app.Dojo'),
        ),
    ]
