# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-20 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ninjas_app', '0004_auto_20170920_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ninja',
            name='dojo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dojo_id', to='Ninjas_app.Dojo'),
        ),
    ]
