# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-20 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ninjas_app', '0006_auto_20170920_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default=0, max_length=1000),
        ),
    ]
